# name: YAML Lint official
# on:
#   push:
#     branches:
#       - "*"
#   pull_request:
#     branches:
#       - "*"

# jobs:
#   yaml-lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Code Checkout
#         uses: actions/checkout@v2
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#           architecture: 'x64'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install yamllint
#       - name: Validate Manifests
#         run: yamllint . -f github
